version: '3'
services:
  node:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      PORT: 8080
      DB_USERNAME: "admin"
      DB_PASSWORD: "adminpw"
      DB_DATABASE: "typeorm"
    links:
        - mysql
  mysql:
    image: mysql:5.7.26
    ports:
      - 3306:3306
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "rootpw"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "adminpw"
      MYSQL_DATABASE: "typeorm"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
networks:
  app-network:
      driver: bridge
